#Due to scikit-learn
FROM python:3.8-slim

#Update packages installed in the image
RUN apt-get update -y

# To fix gcc error during build.
# RUN apt install gcc -y
RUN apt-get install build-essential -y